# Author: Varun Hiremath <vh63@cornell.edu>
# Last Modified:  Thu, 12 Nov 2009 15:46:29 -0500

include ../build-files/vars.windows

LIB_NAME = ck

# ------------- OBJECTS --------------------

include SOURCES.mk

OBJS=$(FILESf:.f=.obj)

# ------------- TARGETS --------------------

all: $(FILES) $(CREATE_LIBS)

include ../build-files/build-targets.windows
