# Author: Varun Hiremath <vh63@cornell.edu>
# Last Modified:  Thu, 12 Nov 2009 16:27:24 -0500

include ../build-files/vars.windows

LIB_NAME = ell

# ------------- OBJECTS --------------------

include SOURCES.mk

OBJS=$(FILESf90:.f90=.obj) $(FILESf:.f=.obj)

# ------------- TARGETS --------------------

all: $(FILES) $(CREATE_LIBS)

include ../build-files/build-targets.windows
